#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/charts/tree/master/charts/common/values.yaml
#

image:
  repository: jonaswinkler/paperless-ng
  pullPolicy: IfNotPresent
  tag: 1.4.5

strategy:
  type: Recreate

# See more environment variables in the ${CHARTNAME} documentation
# https://${CHARTNAME}.org/docs
env: {}
  # TZ:

service:
  port:
    port: 8000

ingress:
  enabled: false

# persistence:
#   data:
#     enabled: false
#     emptyDir: false
#     mountPath: /data
persistence:
  data:
    enabled: true
    mountPath: "/data"
    type: emptyDir
  media:
    enabled: true
    mountPath: "/media"
    type: emptyDir
  consume:
    enabled: true
    mountPath: "/consume"
    type: emptyDir
  export:
    enabled: true
    mountPath: "/export"
    type: emptyDir
  db:
    forceName: "db"
    enabled: true
    type: emptyDir

# Enabled postgres
# ... for more options see https://github.com/bitnami/charts/tree/master/bitnami/postgresql

postgresql:
  enabled: false
  postgresqlUsername: paperless
  postgresqlPassword: paperless
  postgresqlDatabase: paperless
  persistence:
    enabled: false
    existingClaim: db